config/routes.rb
TKArchitecture::Application.routes.draw do

  resource :home, only: [:show]
  root to: "home#show"

  

  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :password_confirmation, :avatar
  has_secure_password
  validates_presence_of :password, :on => :create
  validates :email, uniqueness: true, presence: true

  #use attached file with image paperclip
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
  #helper_method :current_user

  private
  def extract_locale_from_accept_language_header
    begin
      params[:locale] || request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    rescue
      'en'
    end  
  end

  def set_locale
    I18n.locale = extract_locale_from_accept_language_header || I18n.default_locale
  end
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_valid_user
    if session[:user_id] == nil
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :set_locale

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash[:notice] = "Invalid email or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
  end

  def set_locale
    I18n.locale =  params[:locale]
    I18n.default_locale = I18n.locale
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    flash[:notice] = "Hello Flash"
  end

  def home
    flash[:notice] = t(:hello_flash)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_locale

  def new
    @user = User.new
  end

  def create
    if (@user = User.new(params[:user])).save
      redirect_to root_url, notice: "Signed up!"
    else
      render :new
    end
  end

  def set_locale
    I18n.locale =  params[:locale]
    I18n.default_locale = I18n.locale 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<h1>TK Architecture</h1>
<p><%= flash[:notice] %></p>

<h1><%=t :hello_world %></h1>
<p><%= flash[:notice] %></p>

<h1><%=t :hello_world %></h1>
<p><%= flash[:notice] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=<%= locale %> dir=<%= t('directionstring') %>>

<p id="direction_locale" style="display:none;"><%=t('directionstring')%></p>
<script>
  // refresh page when arabic or european language
  var elm = document.body;
  var dir1 = window.getComputedStyle(elm).direction;
  var div = document.getElementById('direction_locale');
  var dir2 = div.innerText;
  if (dir1 != dir2)
    window.location.reload();
</script>


    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/"><%= t 'navigation.home' %></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">
                <a href="/abouts"><%= t 'navigation.about' %></a>
              </li>
              <li class="">
                <a href="/projects"><%= t 'navigation.projects' %></a>
              </li>
              <li class="">
                <a href="/management"><%= t 'navigation.management' %></a>
              </li>
              <li class="active">
                <a href="/contacts"><%= t 'navigation.contacts' %></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TK Architecture" %></title>

    <meta name="description" content="">
    <meta name="author" content="Denis ING">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <p>
    <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
    <%= link_to_unless I18n.locale == :fr, "Français", locale: :fr %>
    <%= link_to_unless I18n.locale == :ar, "العربية", locale: :ar%>
    </p>


    <div id="user_nav">
        <%= link_to "Sign up", sign_up_path+"?locale=#{I18n.locale}" %>
        <%= link_to "log in", login_path+"?locale=#{I18n.locale}" %>
      
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>


    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">

              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

  </body>
</html>

app/views/static_pages/home.html.erb
<h1>TK Architecture</h1>
<p><%= flash[:notice] %></p>

<h1><%=t :hello_world %></h1>
<p><%= flash[:notice] %></p>

<h1><%=t :hello_world %></h1>
<p><%= flash[:notice] %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :avatar, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-6">
      <%= f.file_field :avatar %>
    </div>
  </div>




  <div class="field">
    <%= f.label :email, t('session_user.email') %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, t('session_user.password') %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, t('session_user.password_confirmation') %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>